### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by jabrena** [ExtremeElectronics/PicoCray#5]
Does exist a Video about it?

**Comment by mariobodemann** [comment]
https://twitter.com/ExtElec/status/1644452579223412738?s=20

**Comment by ExtremeElectronics** [comment]
Currently no, I may put up a web page with more detail, when I'm nearer to having everything working.

**Comment by ExtremeElectronics** [comment]
https://twitter.com/i/status/1648401472193720328
